### ISSUE TITLE
Documentation: Old APIs

### ISSUE THREAD

**Issue by ShalokShalom** [fabulous-dev/Fabulous.Avalonia#172]
Hi :)

I remember this project having two different APIs, one inspired by SwiftUI and the classical Elm Architecture. 

I assume, you just went with the former, deleted the old repo, and set up a new project?
It seems a bit confusing for somebody, who wants to catch up, as it seems like I can't trust my memory anymore 😅

**Comment by ShalokShalom** [comment]
I had to dig into the web archive, since this blog post is already deleted for some reason, but yeah, this seems to be the case: https://web.archive.org/web/20220702060529/https://timothelariviere.com/2022/06/01/introducing-fabulous-20/

I suggest mentioning this somewhere on the README and Webpage, as this is just confusing and seems to suggest, that the old way was so bad, that we need to hide this. 

I dont think its the case, so let us maybe add some "History" section, or something. 😅

**Comment by TimLariviere** [comment]
The old DSL was for Fabulous v1 only.

In Fabulous v2, we introduced the SwiftUI-inspired DSL because of several key improvements over the Elmish syntax (less allocations, better handling of obsolete members, more extensible, more IDE-friendly, and so on).
We decided to not port the old DSL to the new version due to low usage and overall improvements of the new syntax.

... and also we decided to split the mono-repo into several repos to accommodate new variants other than Xamarin.Forms. 😅 

You can still find Fabulous v1 in the main repository under the 1.0 branch: https://github.com/fabulous-dev/Fabulous/tree/release/1.0

>I had to dig into the web archive, since this blog post is already deleted for some reason

Sorry about that, I had to change my blog to another place recently. That blog post is still live at https://blog.timothelariviere.com/2022/06/01/introducing-fabulous-20/

>I suggest mentioning this somewhere on the README and Webpage, as this is just confusing and seems to suggest, that the old way was so bad, that we need to hide this.
>
>I dont think its the case, so let us maybe add some "History" section, or something

It's not this bad, but not great neither haha.
But sure, we can add a little explanation somewhere. 😄

**Comment by ShalokShalom** [comment]
I guess simply linking to the old repository would be enough. 
I send a PR.

**Comment by ShalokShalom** [comment]
https://github.com/fabulous-dev/Fabulous.Avalonia/pull/175
